version: '3.9'

services:
  server:
    build:
      context: .
    container_name: server
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      DATABASE_URL: ${DATABASE_URL}

    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - redis
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:6.2.5-alpine
volumes:
  redis-data:
  mysql-data: